build:
  environment:
    php:
      version: 7.1.0
      ini:
        'date.timezone': 'US/Pacific'
  tests:
    override:
      command: 'php codeception.php run unit --coverage --coverage-xml --coverage-html'
      coverage:
        file: 'tests/output/coverage.xml'
        format: 'clover'
