language: php

dist: trusty

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"
    - TASK_TESTS_COVERAGE=0

branches:
  only:
    - feature/tests

services:
  - mysql
  - postgresql

matrix:
  fast_finish: true
  include:
    - php: 7.4snapshot
    - php: 7.3
    - php: 7.2
    # Run tests coverage on PHP 7.1
    - php: 7.1
      env: TASK_TESTS_COVERAGE=1
    - php: 7.0

allow_failures:
  - php: 7.4snapshot

# Cache some folders to speed things up.
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/.npm

# Try running against postgres 9.6
addons:
  postgresql: "9.6"
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

install:
  - |
    if [[ $TASK_TESTS_COVERAGE != 1 ]]; then
      # disable xdebug for performance reasons when code coverage is not needed.
      phpenv config-rm xdebug.ini || echo "xdebug is not installed"
    fi

    # install composer dependencies
    - travis_retry composer self-update
    - export PATH="$HOME/.composer/vendor/bin:$PATH"
    - travis_retry composer install $DEFAULT_COMPOSER_FLAGS
    - touch tests/.env
    - tests/_support/_generated

before_script:
  # show some version and environment information
  - php --version
  - composer --version
  - php -r "echo INTL_ICU_VERSION . \"\n\";"
  - php -r "echo INTL_ICU_DATA_VERSION . \"\n\";"
  - psql --version
  - mysql --version
  -sudo mysql_upgrade

  # initialize database
  - travis_retry mysql -e 'CREATE DATABASE `craft3test`;';
  - mysql -e "SET GLOBAL sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';";
  - mysql -e "CREATE USER 'travis'@'localhost' IDENTIFIED WITH mysql_native_password;";
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'localhost' WITH GRANT OPTION;";
  - psql -U postgres -c 'CREATE DATABASE craft3test;';

script:
  - vendor/bin/codecept run unit --coverage --coverage-xml --coverage-html;

after_script:
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi

#jobs:
#  include:
#    - stage: Static Code Analysis
#      php: 7.3
#      env: php-cs-fixer
#      install:
#        - phpenv config-rm xdebug.ini
#      script:
#        - php-cs-fixer fix --dry-run -v --show-progress=dots --diff-format=udiff