language: php

dist: trusty

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest""

branches:
  only:
    - feature/tests

services:
  - mysql
  - postgresql

matrix:
  fast_finish: true
  include:
    - php: 7.3
    - php: 7.2
    # Run tests coverage on PHP 7.1
    - php: 7.1
      env: TASK_TESTS_COVERAGE=1

# Cache some folders to speed things up.
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/.npm

# Try running against postgres 9.6
addons:
  postgresql: "9.6"
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

install:
  - |
    if [[ $TASK_TESTS_COVERAGE != 1 ]]; then
      # disable xdebug for performance reasons when code coverage is not needed.
      phpenv config-rm xdebug.ini || echo "xdebug is not installed"
    fi

    # install composer dependencies
    export PATH="$HOME/.composer/vendor/bin:$PATH"
    travis_retry composer install $DEFAULT_COMPOSER_FLAGS
    touch tests/.env

before_script:
  - |
    # show some version and environment information
    php --version
    composer --version
    php -r "echo INTL_ICU_VERSION . \"\n\";"
    php -r "echo INTL_ICU_DATA_VERSION . \"\n\";"
    psql --version
    mysql --version

  # initialize database
  - travis_retry mysql -e 'CREATE DATABASE `craft3test`;';
  - mysql -e "SET GLOBAL sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';";
  - psql -U postgres -c 'CREATE DATABASE craft3test;';

  # install imagick
  - pear config-set preferred_state beta
  - pecl channel-update pecl.php.net
  - yes | pecl install imagick

script:
  - |
    if [[ $TASK_TESTS_COVERAGE != 1 ]]; then
      vendor/bin/codecept run unit
    else
      mkdir -p build/logs
      vendor/bin/codecept run unit --coverage-xml build/logs/clover.xml;
    fi

after_script:
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
      travis_retry php vendor/bin/php-coveralls --coverage_clover=tests/_output/build/logs/clover.xml --json_path=tests/_output/build/logs/coveralls-upload.json
    fi

#after_script:
#  - |
#    if [ $TASK_TESTS_COVERAGE == 1 ]; then
#      travis_retry wget https://scrutinizer-ci.com/ocular.phar
#      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
#    fi

#script:
#  - |
#    # if [[ $TASK_TESTS_COVERAGE != 1 ]]; then
#      php -d display_errors=on -d max_execution_time=-1 -d memory_limit=2048M -d error_reporting=-1 vendor/codeception/codeception/codecept run tests/unit/helpers/ArrayHelperTest.php:testToArray;
#    # else
#    #  vendor/bin/codecept run unit --coverage --coverage-xml;
#    # fi

#jobs:
#  include:
#    - stage: Static Code Analysis
#      php: 7.3
#      env: php-cs-fixer
#      install:
#        - phpenv config-rm xdebug.ini
#      script:
#        - php-cs-fixer fix --dry-run -v --show-progress=dots --diff-format=udiff