language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

branches:
  only:
    - feature/tests

env:
  matrix:
    - DRIVER="xdebug"
    - DRIVER="pcov"
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

before_install:
  - composer clear-cache

before_script:
  - |
    if [[ "$DRIVER" = 'pcov' ]]; then
      echo > $HOME/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/conf.d/xdebug.ini
      git clone --single-branch --branch=v1.0.3 --depth=1 https://github.com/krakjoe/pcov
      cd pcov
      phpize
      ./configure
      make clean install
      echo "extension=pcov.so" > $HOME/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/conf.d/pcov.ini
      cd $TRAVIS_BUILD_DIR
    fi

script:
  - vendor/bin/codecept unit --coverage --coverage-xml --coverage-html;

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false

jobs:
  include:
    - stage: Static Code Analysis
      php: 7.3
      env: php-cs-fixer
      install:
        - phpenv config-rm xdebug.ini
      script:
        - php-cs-fixer fix --dry-run -v --show-progress=dots --diff-format=udiff